default-service: Twilio

Twilio:
    sid: -- SID --
    auth_token: -- YOUR_AUTH_TOKEN --
    send_from: your_twilio_number
    incoming_callback_port: 10050
    
    message_queue:
        enabled: true
        interval: 60

        ## Send out all remaining texts when plugin gets disabled
        ## Note: If true you could spam texts and cause whatever service you use to disable your account. It also may cost a lot of money.
        send_remaining_on_disable: false

